spring.application.name=photo-management-backend

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# POSTGRESQL DATABASE
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/photo_management_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Amol@2026Db}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ===============================
# CLOUDFLARE R2
# ===============================

cloudflare.r2.endpoint=https://05e6dd0a2589b89eae44b909c97cd8f7.r2.cloudflarestorage.com
cloudflare.r2.bucket=photo-management

cloudflare.r2.access-key=${R2_ACCESS_KEY_ID}
cloudflare.r2.secret-key=${R2_SECRET_ACCESS_KEY}
# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000
# MAIN ADMIN
app.admin.email=${ADMIN_EMAIL:}
app.admin.password=${ADMIN_PASSWORD:}